export const CANALES_IPC = {
  obtenerConfig: 'config:obtener',
  borrarConfig: 'config:borrar',
  obtenerIpLocal: 'red:obtener-ip-local',
  verificarServidor: 'red:verificar-servidor',
  configurarServidor: 'config:configurar-servidor',
  configurarTerminal: 'config:configurar-terminal',
  iniciarServidorDesdeConfig: 'servidor:iniciar-desde-config',

  authEstadoInicial: 'auth:estado-inicial',
  authCrearPrimerUsuario: 'auth:crear-primer-usuario',
  authLogin: 'auth:login',
  authCerrarSesion: 'auth:cerrar-sesion',
  authSesionActual: 'auth:sesion-actual',
  authReautenticar: 'auth:reautenticar',
  authListarUsuarios: 'auth:listar-usuarios',
  authCrearUsuario: 'auth:crear-usuario',
  authActualizarPermisos: 'auth:actualizar-permisos',
  authRecuperarAcceso: 'auth:recuperar-acceso',
  authResetearAcceso: 'auth:resetear-acceso',

  negocioObtener: 'negocio:obtener',
  negocioGuardar: 'negocio:guardar',
  negocioEstadoRespaldo: 'negocio:respaldo-estado',
  negocioRespaldarAhora: 'negocio:respaldo-ahora',
  negocioListarRespaldos: 'negocio:respaldo-listar',
  negocioRestaurarRespaldo: 'negocio:respaldo-restaurar',

  catalogoListarCategorias: 'catalogo:listar-categorias',
  catalogoCrearCategoria: 'catalogo:crear-categoria',
  catalogoEditarCategoria: 'catalogo:editar-categoria',
  catalogoEliminarCategoria: 'catalogo:eliminar-categoria',

  catalogoListarProductos: 'catalogo:listar-productos',
  catalogoCrearProducto: 'catalogo:crear-producto',
  catalogoEditarProducto: 'catalogo:editar-producto',
  catalogoEliminarProducto: 'catalogo:eliminar-producto',
  catalogoRegistrarEntrada: 'catalogo:registrar-entrada',
  catalogoHistorialEntradas: 'catalogo:historial-entradas',
  catalogoHistorialPrecios: 'catalogo:historial-precios',

  ventasCrear: 'ventas:crear',
  ventasListar: 'ventas:listar',
  ventasObtener: 'ventas:obtener',
  ventasCancelarPausada: 'ventas:cancelar-pausada',
  ventasCancelarActiva: 'ventas:cancelar-activa',
  ventasRegistrarDevolucion: 'ventas:registrar-devolucion',
  ventasListarDevoluciones: 'ventas:listar-devoluciones',

  clientesListar: 'clientes:listar',
  clientesCrear: 'clientes:crear',
  clientesEditar: 'clientes:editar',
  clientesEliminar: 'clientes:eliminar',
  clientesRegistrarAbono: 'clientes:registrar-abono',

  cajaEstablecerFondoInicial: 'caja:establecer-fondo-inicial',
  cajaRegistrarMovimiento: 'caja:registrar-movimiento',
  cajaCerrarTurno: 'caja:cerrar-turno',
  cajaReporteVentas: 'caja:reporte-ventas',
  cajaVentasPorDia: 'caja:ventas-por-dia',
  cajaVentasPorCajero: 'caja:ventas-por-cajero',
  cajaListarCortes: 'caja:listar-cortes',
  cajaMovimientosTurno: 'caja:movimientos-turno',
  cajaReporteDevoluciones: 'caja:reporte-devoluciones',
  cajaResumenTurno: 'caja:resumen-turno',
  cajaDevolucionesTurno: 'caja:devoluciones-turno',
  cajaObtenerFondoInicial: 'caja:obtener-fondo-inicial',

  proveedoresListar: 'proveedores:listar',
  proveedoresCrear: 'proveedores:crear',
  proveedoresEditar: 'proveedores:editar',
  proveedoresEliminar: 'proveedores:eliminar',

  comprasCrear: 'compras:crear',
  comprasListar: 'compras:listar',
  comprasObtener: 'compras:obtener',

  mermasRegistrar: 'mermas:registrar',
  mermasHistorial: 'mermas:historial',

  promocionesListar: 'promociones:listar',
  promocionesListarActivas: 'promociones:listar-activas',
  promocionesCrear: 'promociones:crear',
  promocionesEditar: 'promociones:editar',
  promocionesEliminar: 'promociones:eliminar',

  basculaLeerPeso: 'bascula:leer-peso',

  impresoraImprimirTicket: 'impresora:imprimir-ticket',
  impresoraAbrirCajon: 'impresora:abrir-cajon'
} as const
